
module.exports = {
    
    MSGS: {
    SHOW_FORM: 'SHOW_FORM',
    CROP_KIND_INPUT: 'CROP_KIND_INPUT',
    CROP_QUANTITY_INPUT: 'CROP_QUANTITY_INPUT',
    UNIT_PRICE_INPUT: 'UNIT_PRICE_INPUT',
    SAVE_CROP_RECORD: 'SAVE_CROP_RECORD',
    DELETE_CROP_RECORD: 'DELETE_CROP_RECORD',
    EDIT_CROP_RECORD: 'EDIT_CROP_RECORD',
    },

}